[workspace.package]
version = "0.1.0"

[workspace]

members = [
    "despatma",
    "despatma-lib",
    "despatma-test-helpers"
]

[workspace.dependencies]
pretty_assertions = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
tokenstream2-tmpl = "0.1"
