[package]
name = "despatma-test-helpers"
version = "0.1.0"
authors = ["chesedo <pieter@chesedo.me>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = { workspace = true }
