[package]
name = "despatma"
version = "0.1.0"
authors = ["chesedo <pieter@chesedo.me>"]
edition = "2018"
description = "Design Pattern Macro like Loki"
repository = "https://github.com/chesedo/despatma"
license = "MIT"
keywords = ["macro", "design", "patterns"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
despatma-lib = { path = "../despatma-lib", version = "0.1.0" }

proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
tokenstream2-tmpl = { workspace = true }


[dev-dependencies]
despatma-test-helpers = { path = "../despatma-test-helpers" }
despatma-lib = { path = "../despatma-lib", features = ["extra-traits"] }
macrotest = "1.0"
pretty_assertions = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }
trybuild = "1.0"
